"use client";
import ExcelJS from "exceljs";

export default function ExportExcelButton({ session, participants }: { session: any, participants: any[] }) {
  const handleExport = async () => {
    const totalQuestions = session.quiz.questions.length;
    
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Leaderboard");

    // Fetch and add logo
    try {
      const response = await fetch("/Picture/logo/2.jpg");
      const imageBuffer = await response.arrayBuffer();
      const logoId = workbook.addImage({
        buffer: imageBuffer,
        extension: 'jpeg',
      });
      worksheet.addImage(logoId, {
        tl: { col: 0, row: 0 },
        ext: { width: 160, height: 60 } // reasonable logo size
      });
    } catch (e) {
      console.error("Could not load logo", e);
    }

    // Leave space for logo
    worksheet.addRow([]);
    worksheet.addRow([]);
    worksheet.addRow([]);
    worksheet.addRow([]);

    // Title and Info
    const titleRow = worksheet.addRow(["QUIZZ RESULT REPORT"]);
    titleRow.font = { size: 16, bold: true, color: { argb: "FF6B21A8" } }; // brand-purple roughly
    worksheet.addRow(["Session Name:", session.name || session.quiz?.title || "Unknown"]);
    worksheet.addRow(["Session Code:", session.code]);
    worksheet.addRow(["Total Players:", participants.length]);
    worksheet.addRow([]);

    // Headers
    const headerRow = worksheet.addRow([
      "Rank",
      "Nickname",
      "Correct Answers",
      "Incorrect Answers",
      "Total Answered",
      "Score"
    ]);
    headerRow.font = { bold: true };
    headerRow.fill = {
      type: 'pattern',
      pattern:'solid',
      fgColor:{ argb:'FFF3F4F6' }
    };

    // Data rows
    participants.forEach((p, index) => {
       const progress = p.answers?.length || 0;
       const correctCount = p.answers?.filter((a: any) => a.isCorrect).length || 0;
       const incorrectCount = progress - correctCount;
       
       worksheet.addRow([
         index + 1,
         p.nickname,
         correctCount,
         incorrectCount,
         progress + " / " + totalQuestions,
         p.score
       ]);
    });

    // Spacer
    worksheet.addRow([]);
    worksheet.addRow([]);

    // Footer info
    const footerRow = worksheet.addRow(["Generated by Open Quizz Platform • open-quizz.vercel.app"]);
    footerRow.font = { italic: true, color: { argb: "FF9CA3AF" } };

    // Column formatting
    worksheet.columns = [
      { width: 10 }, // Rank
      { width: 30 }, // Nickname
      { width: 18 }, // Correct
      { width: 18 }, // Incorrect
      { width: 18 }, // Total Answered
      { width: 15 }  // Score
    ];

    // Generate output
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `Leaderboard_${session.code || 'Export'}.xlsx`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <button 
      onClick={handleExport}
      className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-xl flex items-center gap-2 transition shadow-sm border-b-4 border-green-800 active:border-b-0 active:translate-y-1"
    >
      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
      </svg>
      Export Excel
    </button>
  );
}
